server:
  port: 8080

spring:
  application:
    name: "AuthService"
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/powerup
    username: postgres
    password: 123456789
  h2:
    console:
      enabled: true
      path: "/h2"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
